### ISSUE TITLE
Toggle between search algorithms

### ISSUE THREAD

**Issue by colliecoder** [colliecoder/maze-winner#18]
Create a way to toggle between search algorithms so that the user can select the search algorithm for generating the maze. 

Likewise, implement this solution for toggling between search algorithms that solve the maze.

**Comment by A-Spiral-Forge** [comment]
Hey, I want to work on this please assign this to me.

**Comment by colliecoder** [comment]
Any update on this?

**Comment by A-Spiral-Forge** [comment]
@colliecoder sorry for inconvenience I was busy in college projects. I will currently not able to work on it,

**Comment by colliecoder** [comment]
@A-Spiral-Forge No problem! School projects definitely have to come first - thanks for letting me know.
