### ISSUE TITLE
Create functions for maze_solver.js

### ISSUE THREAD

**Issue by colliecoder** [colliecoder/maze-winner#6]
maze_solver.js needs to have the functions for solving the maze using search algorithms added, pseudocode from the functions copied down and any common sequences of code related to the algorithms programmed in the form of functions. 

Check out these wikipedia pages for common algorithms used in maze solving:
[Maze Solving Algorithms Wiki](https://en.wikipedia.org/wiki/Maze-solving_algorithm)

Some common algorithms for solving mazes include left or right wall following, depth first search, Manhattan distance and shortest path algorithms such as A*. Essentially the goal of this issue is to set up maze_solver.js with everything it needs to have other than coding the maze solving algorithms themselves.

**Comment by bettoarcaya** [comment]
Do you have a list of the algorithms that are needed? just to know which one I can work on.
or even better could you create separate issues for any algorithm needed in maze solver.js?

**Comment by colliecoder** [comment]
@bettoarcaya I updated the description and title of this post for clarity! Let me know if you would like to work on this or have any more questions about the issue.

**Comment by bettoarcaya** [comment]
okay, thanks. 
I would like to work on this, please assign it to me.

**Comment by colliecoder** [comment]
Any update on this?

**Comment by bettoarcaya** [comment]
Hi.
Working on it.
I probably will finish in one or two days.
